---
title: DAHC
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
description: 'The Digital Arts & Humanities Commons at UCSB'
author: DAHC Admin
email: dahc@hfa.ucsb.edu
theme: jekyll-theme-leap-day
permalink: "/posts/:title"
baseurl: ""
url: https://DAHCommons.github.io
google_analytics: 
---
